In [1]:
#lib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(palette='rainbow')

## WORKING WITH ONLY LOGISTIC REGRESSION

In [2]:
from sklearn.linear_model import LogisticRegression

#### Laoding the data

In [5]:
data = pd.read_csv('ready_data.csv')

In [6]:
data.head()

r_type1  r_type2  r_type3  r_type4  Month_value  week_day  \
0        0        0        0        1            7         1   
1        0        0        0        0            7         1   
2        0        0        0        0            7         2   
3        1        0        0        0            7         3   
4        0        0        0        0            7         3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [8]:
#Preparing Target Column

data=data.rename(columns = {'Absenteeism Time in Hours':'target'})

In [9]:
data.head(1)

r_type1  r_type2  r_type3  r_type4  Month_value  week_day  \
0        0        0        0        1            7         1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  target  
0               30          1         2     1       4

In [22]:
data['target'].median()

3.0

In [20]:
data['target'].max()

120

In [21]:
data['target'].min()

0

In [23]:
#Categorizing the ['target'] column
#everyone who is absent more than 3 hours will be mark as Excessive absenteeism and the lower value of 3 means moderate absent

In [26]:
targets = np.where(data['target']>np.median(data['target']),1,0)

In [27]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [28]:
df = data.copy()

In [29]:
df.drop('target',axis=1,inplace=True)

In [30]:
df['target'] = targets

In [31]:
df['target'].value_counts()

0    381
1    319
Name: target, dtype: int64

#### FEATURE AND TARGET

In [36]:
featured_x = df.iloc[:,:-1]
target_y = df['target']

In [43]:
featured_x.shape, target_y.shape ,df.shape

((700, 14), (700,), (700, 15))

In [44]:
### Standardize data

In [45]:
featured_x.describe()

r_type1     r_type2     r_type3     r_type4  Month_value  \
count  700.000000  700.000000  700.000000  700.000000   700.000000   
mean     0.227143    0.005714    0.105714    0.341429     6.897143   
std      0.419285    0.075431    0.307691    0.474528     3.342319   
min      0.000000    0.000000    0.000000    0.000000     1.000000   
25%      0.000000    0.000000    0.000000    0.000000     4.000000   
50%      0.000000    0.000000    0.000000    0.000000     7.000000   
75%      0.000000    0.000000    0.000000    1.000000    10.000000   
max      1.000000    1.000000    1.000000    1.000000    12.000000   

         week_day  Transportation Expense  Distance to Work         Age  \
count  700.000000              700.000000        700.000000  700.000000   
mean     2.410000              222.347143         29.892857   36.417143   
std      1.761669               66.312960         14.804446    6.379083   
min      0.000000              118.000000          5.000000   27.000000   
25%      1.000000              179.000000         16.000000   31.000000   
50%      2.000000              225.000000         26.000000   37.000000   
75%      4.000000              260.000000         50.000000   40.000000   
max      6.000000              388.000000         52.000000   58.000000   

       Daily Work Load Average  Body Mass Index   Education    Children  \
count               700.000000       700.000000  700.000000  700.000000   
mean                271.801774        26.737143    1.282857    1.021429   
std                  40.021804         4.254701    0.668090    1.112215   
min                 205.917000        19.000000    1.000000    0.000000   
25%                 241.476000        24.000000    1.000000    0.000000   
50%                 264.249000        25.000000    1.000000    1.000000   
75%                 294.217000        31.000000    1.000000    2.000000   
max                 378.884000        38.000000    4.000000    4.000000   

             Pets  
count  700.000000  
mean     0.687143  
std      1.166095  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      8.000000

In [46]:
from sklearn.preprocessing import StandardScaler

scalerDF = StandardScaler()

In [47]:
scalerDF.fit(featured_x)

StandardScaler()

In [49]:
scaled_x = scalerDF.transform(featured_x)

In [50]:
scaled_x

array([[-0.54212562, -0.0758098 , -0.34381807, ..., -0.42368477,
         0.88046927,  0.26848661],
       [-0.54212562, -0.0758098 , -0.34381807, ..., -0.42368477,
        -0.01928035, -0.58968976],
       [-0.54212562, -0.0758098 , -0.34381807, ..., -0.42368477,
        -0.91902997, -0.58968976],
       ...,
       [ 1.84459094, -0.0758098 , -0.34381807, ...,  1.07419067,
        -0.91902997, -0.58968976],
       [-0.54212562, -0.0758098 , -0.34381807, ...,  2.57206611,
        -0.91902997, -0.58968976],
       [-0.54212562, -0.0758098 , -0.34381807, ..., -0.42368477,
        -0.01928035,  0.26848661]])

## CUSTOM SCALER FOR OMITING BINARY COLUMN

In [104]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler


class CustomScaler(BaseEstimator,TransformerMixin): 
    
    
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        
        self.scaler = StandardScaler(copy,with_mean,with_std)
       
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    

    def transform(self, X, y=None, copy=None):
        
        
        init_col_order = X.columns
        
        
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
       
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [111]:
columns_to_omit = ['r_type1', 'r_type2', 'r_type3', 'r_type4','Education']
columns_to_scale = [x for x in featured_x.columns.values if x not in columns_to_omit]

In [112]:
custom_scalerDF = CustomScaler(columns_to_scale)

C:\Users\Nill\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


In [113]:
custom_scalerDF.fit(featured_x)

C:\Users\Nill\AppData\Roaming\Python\Python37\site-packages\sklearn\base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month_value', 'week_day', 'Transportation Expense',
                      'Distance to Work', 'Age', 'Daily Work Load Average',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [114]:
custom_scaled_inputs = custom_scalerDF.transform(featured_x)

In [115]:
custom_scaled_inputs

r_type1  r_type2  r_type3  r_type4  Month_value  week_day  \
0          0        0        0        1     0.030796 -0.800950   
1          0        0        0        0     0.030796 -0.800950   
2          0        0        0        0     0.030796 -0.232900   
3          1        0        0        0     0.030796  0.335149   
4          0        0        0        0     0.030796  0.335149   
5          0        0        0        0     0.929019 -0.232900   
6          0        0        1        0     0.030796  0.903199   
7          0        0        0        0     0.030796  0.903199   
8          0        0        1        0    -0.268611  2.039298   
9          0        0        1        0     0.030796 -1.368999   
10         0        0        0        0     0.030796 -1.368999   
11         0        0        0        0     0.030796 -0.800950   
12         1        0        0        0     0.030796 -0.232900   
13         1        0        0        0     0.030796 -0.232900   
14         0        0        0        0     0.030796 -0.232900   
15         1        0        0        0     0.030796  0.903199   
16         0        0        0        0     0.030796  0.903199   
17         0        0        1        0     0.030796 -1.368999   
18         1        0        0        0     0.030796  0.335149   
19         0        0        0        0    -0.568019  0.903199   
20         1        0        0        0     1.527833 -0.800950   
21         1        0        0        0    -1.166834  2.039298   
22         1        0        0        0     0.929019  0.335149   
23         0        0        0        1     0.330204  0.903199   
24         0        0        0        0     0.330204 -1.368999   
25         0        0        0        1     0.330204 -1.368999   
26         0        0        0        0    -0.867426 -0.232900   
27         0        0        0        1     1.527833 -0.800950   
28         0        0        0        0     0.330204 -0.232900   
29         0        0        0        0     0.330204  0.903199   
30         0        0        0        0     0.330204 -1.368999   
31         0        0        0        0     0.330204  0.335149   
32         0        0        0        0     0.330204  0.335149   
33         0        0        0        0     0.330204 -1.368999   
34         0        0        0        0     0.330204 -1.368999   
35         0        0        0        0     0.330204 -1.368999   
36         0        0        0        1    -0.867426 -0.232900   
37         1        0        0        0     0.330204  0.335149   
38         0        0        0        1     0.330204  0.903199   
39         0        0        0        0     0.330204  0.903199   
40         0        0        0        0    -1.765648  0.903199   
41         0        0        0        0     0.030796  0.335149   
42         0        0        0        0    -1.765648  0.903199   
43         0        0        1        0     0.330204  2.039298   
44         0        0        0        0     0.629611 -0.232900   
45         0        0        0        0     0.629611  2.039298   
46         0        0        0        0     0.629611 -1.368999   
47         0        0        0        0     0.629611  0.335149   
48         0        0        1        0    -0.867426  0.335149   
49         1        0        0        0     0.629611 -1.368999   
50         0        0        0        0     0.629611 -1.368999   
51         0        0        0        0     0.629611 -1.368999   
52         0        0        0        0     0.330204  2.039298   
53         0        0        0        0     0.629611 -0.800950   
54         0        0        0        0     0.629611 -0.800950   
55         0        0        0        0     0.629611 -0.800950   
56         0        0        0        0     0.629611 -0.232900   
57         0        0        0        0     0.629611 -0.232900   
58         0        0        0        0     0.629611 -0.232900   
59         0        0        0        0     1

#### Train Test Split

In [51]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,y_train,y_test = train_test_split(scaled_x,target_y,test_size=0.2,random_state=12)

In [56]:
x_train.shape,y_train.shape

((560, 14), (560,))

In [57]:
x_test.shape,y_test.shape

((140, 14), (140,))

In [58]:
### Logistic Regression (Classifier Model)

### Train Test Split with Custom Scaler

In [116]:
x2_train,x2_test,y2_train,y2_test = train_test_split(custom_scaled_inputs,target_y,test_size=0.2,random_state=12)

### MODEL

In [59]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [61]:
model.score(x_test,y_test) #Baseline Accuracy

0.7214285714285714

### CUSTOM SCALER ACCURACY

In [117]:
model.fit(x2_train,y2_train)

LogisticRegression()

In [118]:
model.score(x2_test,y2_test)

0.7285714285714285

#### Predicting the model

In [63]:
y_predict = model.predict(x_train)

In [65]:
np.sum(y_predict == y_train)

425

In [67]:
y_predict.shape[0]

560

In [68]:
np.sum(y_predict == y_train) /  y_predict.shape[0] ## ACCURACY

0.7589285714285714

#### FEATURE IMPORTANCE

In [70]:
model.intercept_

array([-0.19878149])

In [71]:
model.coef_

array([[ 0.83621057,  0.09011191,  0.89324739,  0.13727998,  0.09074958,
        -0.17367392,  0.52281722, -0.09480764, -0.12909027, -0.02490463,
         0.07640924, -0.09288892,  0.37006707, -0.30193717]])

In [85]:
column_name = featured_x.columns.values

In [86]:
model_summary = pd.DataFrame(columns=['Feature_Name'],data=column_name)

In [87]:
model_summary['Coefficient'] = np.transpose(model.coef_)

In [88]:
#adding intercept to the dataFrame
model_summary.index = model_summary.index+1
model_summary.loc[0] = ['Intercept',model.intercept_[0]]


In [89]:
model_summary = model_summary.sort_index()

In [90]:
model_summary

Feature_Name  Coefficient
0                 Intercept    -0.198781
1                   r_type1     0.836211
2                   r_type2     0.090112
3                   r_type3     0.893247
4                   r_type4     0.137280
5               Month_value     0.090750
6                  week_day    -0.173674
7    Transportation Expense     0.522817
8          Distance to Work    -0.094808
9                       Age    -0.129090
10  Daily Work Load Average    -0.024905
11          Body Mass Index     0.076409
12                Education    -0.092889
13                 Children     0.370067
14                     Pets    -0.301937

In [91]:
model_summary['Odd Ratio'] = np.exp(model_summary['Coefficient'])

In [93]:
model_summary

Feature_Name  Coefficient  Odd Ratio
0                 Intercept    -0.198781   0.819729
1                   r_type1     0.836211   2.307606
2                   r_type2     0.090112   1.094297
3                   r_type3     0.893247   2.443050
4                   r_type4     0.137280   1.147149
5               Month_value     0.090750   1.094995
6                  week_day    -0.173674   0.840571
7    Transportation Expense     0.522817   1.686773
8          Distance to Work    -0.094808   0.909548
9                       Age    -0.129090   0.878895
10  Daily Work Load Average    -0.024905   0.975403
11          Body Mass Index     0.076409   1.079404
12                Education    -0.092889   0.911295
13                 Children     0.370067   1.447832
14                     Pets    -0.301937   0.739385

* If the coef is almost 0 and the odd ratio is almost 1 that feature is not important enough for prediction


In [94]:
 model_summary.sort_values('Odd Ratio',ascending=False)

Feature_Name  Coefficient  Odd Ratio
3                   r_type3     0.893247   2.443050
1                   r_type1     0.836211   2.307606
7    Transportation Expense     0.522817   1.686773
13                 Children     0.370067   1.447832
4                   r_type4     0.137280   1.147149
5               Month_value     0.090750   1.094995
2                   r_type2     0.090112   1.094297
11          Body Mass Index     0.076409   1.079404
10  Daily Work Load Average    -0.024905   0.975403
12                Education    -0.092889   0.911295
8          Distance to Work    -0.094808   0.909548
9                       Age    -0.129090   0.878895
6                  week_day    -0.173674   0.840571
0                 Intercept    -0.198781   0.819729
14                     Pets    -0.301937   0.739385

## checking the accuracy difference between train and test data

In [95]:
model.score(x_train,y_train)

0.7589285714285714

In [96]:
model.score(x_test,y_test)

0.7214285714285714

* It's normal that test accuracy will always be lower than train accuracy
* If there is a difference between train accuracy and test accuracy is higher that means the data overfit the model that's why it showing poor accuracy on test data

In [97]:
#checking the probability of getting 1 and getting 0
predicted_proba = model.predict_proba(x_test)
     

In [98]:
predicted_proba

array([[0.75522093, 0.24477907],
       [0.38174782, 0.61825218],
       [0.86992174, 0.13007826],
       [0.65662988, 0.34337012],
       [0.77104319, 0.22895681],
       [0.82592024, 0.17407976],
       [0.13738853, 0.86261147],
       [0.37776984, 0.62223016],
       [0.54080589, 0.45919411],
       [0.79662864, 0.20337136],
       [0.49569644, 0.50430356],
       [0.50317677, 0.49682323],
       [0.69525298, 0.30474702],
       [0.39753492, 0.60246508],
       [0.69925984, 0.30074016],
       [0.55002162, 0.44997838],
       [0.82015069, 0.17984931],
       [0.26625083, 0.73374917],
       [0.71127508, 0.28872492],
       [0.36638849, 0.63361151],
       [0.35692896, 0.64307104],
       [0.44366309, 0.55633691],
       [0.71776761, 0.28223239],
       [0.43103448, 0.56896552],
       [0.06408391, 0.93591609],
       [0.80512762, 0.19487238],
       [0.68110024, 0.31889976],
       [0.85657091, 0.14342909],
       [0.84998532, 0.15001468],
       [0.04889556, 0.95110444],
       [0.

In [101]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.DataFrame(columns=['No','Yes'],data=predicted_proba)

No       Yes
0    0.755221  0.244779
1    0.381748  0.618252
2    0.869922  0.130078
3    0.656630  0.343370
4    0.771043  0.228957
5    0.825920  0.174080
6    0.137389  0.862611
7    0.377770  0.622230
8    0.540806  0.459194
9    0.796629  0.203371
10   0.495696  0.504304
11   0.503177  0.496823
12   0.695253  0.304747
13   0.397535  0.602465
14   0.699260  0.300740
15   0.550022  0.449978
16   0.820151  0.179849
17   0.266251  0.733749
18   0.711275  0.288725
19   0.366388  0.633612
20   0.356929  0.643071
21   0.443663  0.556337
22   0.717768  0.282232
23   0.431034  0.568966
24   0.064084  0.935916
25   0.805128  0.194872
26   0.681100  0.318900
27   0.856571  0.143429
28   0.849985  0.150015
29   0.048896  0.951104
30   0.691587  0.308413
31   0.742045  0.257955
32   0.516593  0.483407
33   0.796629  0.203371
34   0.515921  0.484079
35   0.737317  0.262683
36   0.051382  0.948618
37   0.794007  0.205993
38   0.738364  0.261636
39   0.751440  0.248560
40   0.446437  0.553563
41   0.214288  0.785712
42   0.820151  0.179849
43   0.805137  0.194863
44   0.843457  0.156543
45   0.748241  0.251759
46   0.871973  0.128027
47   0.771093  0.228907
48   0.589800  0.410200
49   0.574110  0.425890
50   0.455464  0.544536
51   0.655984  0.344016
52   0.788766  0.211234
53   0.468151  0.531849
54   0.497794  0.502206
55   0.805128  0.194872
56   0.803919  0.196081
57   0.645568  0.354432
58   0.076028  0.923972
59   0.550599  0.449401
60   0.552600  0.447400
61   0.802046  0.197954
62   0.777137  0.222863
63   0.611805  0.388195
64   0.527142  0.472858
65   0.452909  0.547091
66   0.762791  0.237209
67   0.136400  0.863600
68   0.846556  0.153444
69   0.814055  0.185945
70   0.733270  0.266730
71   0.697360  0.302640
72   0.206731  0.793269
73   0.369710  0.630290
74   0.109768  0.890232
75   0.455638  0.544362
76   0.041359  0.958641
77   0.745605  0.254395
78   0.572376  0.427624
79   0.818961  0.181039
80   0.804591  0.195409
81   0.349985  0.650015
82   0.733064  0.266936
83   0.503059  0.496941
84   0.876425  0.123575
85   0.146244  0.853756
86   0.676686  0.323314
87   0.112499  0.887501
88   0.076333  0.923667
89   0.796293  0.203707
90   0.379829  0.620171
91   0.657282  0.342718
92   0.687790  0.312210
93   0.641688  0.358312
94   0.789191  0.210809
95   0.302157  0.697843
96   0.367262  0.632738
97   0.374162  0.625838
98   0.204058  0.795942
99   0.125230  0.874770
100  0.848413  0.151587
101  0.799113  0.200887
102  0.546674  0.453326
103  0.807946  0.192054
104  0.297325  0.702675
105  0.302794  0.697206
106  0.070966  0.929034
107  0.319126  0.680874
108  0.744511  0.255489
109  0.206731  0.793269
110  0.221652  0.778348
111  0.603843  0.396157
112  0.836900  0.163100
113  0.455288  0.544712
114  0.034311  0.965689
115  0.785882  0.214118
116  0.407109  0.592891
117  0.195163  0.804837
118  0.729174  0.270826
119  0.748678  0.251322
120  0.830676  0.169324
121  0.418761  0.581239
122  0.424074  0.575926
123  0.486758  0.513242
124  0.848914  0.151086
125  0.885786  0.114214
126  0.329733  0.670267
127  0.848413  0.151587
128  0.702386  0.297614
129  0.721737  0.278263
130  0.743579  0.256421
131  0.116756  0.883244
132  0.456876  0.543124
133  0.847529  0.152471
134  0.260582  0.739418
135  0.715664  0.284336
136  0.855493  0.144507
137  0.083641  0.916359
138  0.770752  0.229248
139  0.770946  0.229054

### SAVING THE MODEL

In [102]:
import pickle

In [103]:
with open('model','wb') as file:
    pickle.dump(model,file)

### Saving the Scaler

In [120]:
with open('scaler','wb') as file:
    pickle.dump(scalerDF,file)

### Saving the Custom Scaler

In [121]:
with open('customScaler','wb') as file:
    pickle.dump(custom_scalerDF,file)